name: Create Versions.json every day

# Controls when the workflow will run
on:
 
  # schedule action to run 9 am everyday
  workflow_dispatch:

# run all jobs one by one
jobs:
  run-once:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to repo
        uses: actions/checkout@v3

      - name: Install unzip
        run: sudo apt-get update && sudo apt-get install -y unzip

      - name: Download environment file
        run: |
          echo "Starting the download"
          wget https://download.moodle.org/environment/environment.zip -O environment.zip
          echo "Download completed"
      
      - name: Unzip file
        run: yes | unzip environment.zip 

      - name: Download Versions file
        run: |
          echo "Starting the download"
          wget https://raw.githubusercontent.com/moodle/devdocs/main/data/versions.json -O moodleVersions.json
          echo "Download completed"
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: Install Dependencies
        run: npm install --prefix githubActions/

      - name: Run JS file
        run: node githubActions/versionJsonScript.js

      - name: Check for errors
        if: ${{ failure() }}
        run: |
          echo "There was an error running the script."
          echo "Error message: ${{ job.status }}"
          exit 1
      - name: Delete files
        run: rm -rf moodleVersions.json ./environment environment.zip

      - name: Create pull request
        id: cpr
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: 'Add versions.json'
          branch: addVersionsJson
          title: 'Updated data/versions.json'
          body: 'Updated versions.json file'
          labels: 'file'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
